projects:
  cats:
    schemaPath: amplify/backend/api/cats/build/schema.graphql
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/components/API.ts
        docsFilePath: src/graphql
extensions:
  amplify:
    version: 3
